# Uncomment this line to define a global platform for your project
platform :ios, '12.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'
ENV['SWIFT_VERSION'] = '5'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup



target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))

#  pod 'AlivcConan', :git => 'https://github.com/aliyunvideo/AlivcConanSDK.git',:tag => '1.0.2'
#  pod 'AliyunVideoSDKStd', :git => 'https://github.com/aliyunvideo/AliyunVideoSDKStd.git',:tag => '3.14.0'
#  pod 'QuCore-ThirdParty', :git => 'https://github.com/aliyunvideo/QuCore-ThirdParty.git',:tag => '3.10.0'
#  pod 'VODUpload',:git => 'https://github.com/aliyunvideo/VODUpload.git',:tag => '1.5.3'

  pod 'AliyunVideoSDKStd', '3.17.1'
  pod 'QuCore-ThirdParty', '3.15.0' #// the problem one
  pod 'AlivcConan', '1.0.3'
  pod 'VODUpload'
  pod 'AliyunOSSiOS'

end

post_install do |installer|
 installer.pods_project.targets.each do |target|
   flutter_additional_ios_build_settings(target)
   target.build_configurations.each do |config|
     config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.0'
   end
 end
end


